// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EmployeeGetterRequest struct {
	EmpID *string `json:"empId"`
	Title *string `json:"title"`
}

type EmployeeGetterResponse struct {
	Error       bool         `json:"error"`
	Message     string       `json:"message"`
	EmployeeGet []*Employees `json:"employeeGet"`
}

type EmployeeRequest struct {
	EmpID     *string `json:"empId"`
	Firstname string  `json:"firstname"`
	Lastname  string  `json:"lastname"`
	Title     string  `json:"title"`
	Address   string  `json:"address"`
}

type Employees struct {
	EmpID     string `json:"empId"`
	Title     string `json:"title"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Address   string `json:"address"`
}

type Response struct {
	Error   bool   `json:"error"`
	Message string `json:"message"`
}
